### ISSUE TITLE
No enum constant com.aliyun.dts.subscribe.clients.record.value.ObjectType.JSONB

### ISSUE THREAD

**Issue by naaive** [aliyun/aliyun-dts-subscribe-sdk-java#26]
```
java.lang.IllegalArgumentException: No enum constant com.aliyun.dts.subscribe.clients.record.value.ObjectType.JSONB
	at java.lang.Enum.valueOf(Enum.java:238) ~[na:1.8.0_342]
	at com.aliyun.dts.subscribe.clients.record.value.ObjectType.valueOf(ObjectType.java:3) ~[dts-new-subscribe-sdk-1.4.1.jar:na]
	at com.aliyun.dts.subscribe.clients.formats.avro.DefaultValueDeserializer.deserialize(DefaultValueDeserializer.java:58) ~[dts-new-subscribe-sdk-1.4.1.jar:na]
	at com.aliyun.dts.subscribe.clients.record.AvroRecordParser.getRowImage(AvroRecordParser.java:198) ~[dts-new-subscribe-sdk-1.4.1.jar:na]
	at com.aliyun.dts.subscribe.clients.record.DefaultUserRecord.lambda$getAfterImage$2(DefaultUserRecord.java:84) ~[dts-new-subscribe-sdk-1.4.1.jar:na]
```

**Comment by naaive** [comment]
PostgreSQL 14.4
